# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38d0d41f2c2340b59886ed4d4c98c723364103d37b3c83870442d1e417fd5478bc87dcb89df6d2c371d396a7a811d5e5431c1961b6ba80d90ae968231f1613ce

test:
  secret_key_base: aff91141199f8a3b0ec5c10468c00dfa49013a53903a6f7e150cc0132393e1d6434eaa16a1d11b5cbdcf8bdcc6d41b35e73184ecafc6b8e8910a70629596c5c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
